# Generated by Django 5.1.1 on 2024-10-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
    ]
