# Generated by Django 4.2.16 on 2024-10-15 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0004_list_item'),
        ('projectApp', '0004_remove_user_created_user_is_admin'),
    ]

    operations = [
    ]
