# Generated by Django 5.1.2 on 2024-10-15 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0005_merge_20241014_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='url',
        ),
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectApp.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
